// <auto-generated />
using System;
using JapaneseFlashcardAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JapaneseFlashcardAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired().HasMaxLength(256).HasColumnType("nvarchar(256)");
                b.Property<string>("PasswordHash")
                    .IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Username")
                    .IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");

                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.Deck", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Decks");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.Flashcard", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("DeckId").HasColumnType("int");
                b.Property<decimal>("EaseFactor").HasColumnType("decimal(5,2)");
                b.Property<string>("ExampleSentence").HasMaxLength(1000).HasColumnType("nvarchar(1000)");
                b.Property<int>("Interval").HasColumnType("int");
                b.Property<string>("Kanji").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Meaning").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                b.Property<DateTime>("NextReviewDate").HasColumnType("datetime2");
                b.Property<string>("Reading").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");

                b.HasKey("Id");
                b.HasIndex("DeckId");
                b.ToTable("Flashcards");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.ReviewLog", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("FlashcardId").HasColumnType("int");
                b.Property<int>("Rating").HasColumnType("int");
                b.Property<DateTime>("ReviewedAt").HasColumnType("datetime2");
                b.Property<int>("UserId").HasColumnType("int");

                b.HasKey("Id");
                b.HasIndex(new[] { "FlashcardId", "ReviewedAt" }, name: "IX_ReviewLogs_FlashcardId_ReviewedAt");
                b.HasIndex("UserId");
                b.ToTable("ReviewLogs");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.Deck", b =>
            {
                b.HasOne("JapaneseFlashcardAPI.Domain.Entities.User", "User")
                    .WithMany("Decks").HasForeignKey("UserId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.Flashcard", b =>
            {
                b.HasOne("JapaneseFlashcardAPI.Domain.Entities.Deck", "Deck")
                    .WithMany("Flashcards").HasForeignKey("DeckId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Deck");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.ReviewLog", b =>
            {
                b.HasOne("JapaneseFlashcardAPI.Domain.Entities.Flashcard", "Flashcard")
                    .WithMany("ReviewLogs").HasForeignKey("FlashcardId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("JapaneseFlashcardAPI.Domain.Entities.User", "User")
                    .WithMany("ReviewLogs").HasForeignKey("UserId").OnDelete(DeleteBehavior.NoAction).IsRequired();
                b.Navigation("Flashcard");
                b.Navigation("User");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.User", b =>
            {
                b.Navigation("Decks");
                b.Navigation("ReviewLogs");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.Deck", b =>
            {
                b.Navigation("Flashcards");
            });

            modelBuilder.Entity("JapaneseFlashcardAPI.Domain.Entities.Flashcard", b =>
            {
                b.Navigation("ReviewLogs");
            });
#pragma warning restore 612, 618
        }
    }
}
