name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kyhieu/japane-learn:latest

  deploy_ubuntu:
    needs: build_job
    runs-on: self-hosted
    steps:
      - name: Deploy on Local Server
        run: |
          cd ~/app/japane-learn-prod
          # 1. Cập nhật file docker-compose.yml và cấu hình mới nhất từ git
          git fetch origin main
          git reset --hard origin/main
          
          # 2. Tải ảnh mới nhất từ Docker Hub
          docker compose pull api
          
          # 3. Khởi động lại container bằng ảnh mới (chỉ mất vài giây, không cần down trước để giảm downtime)
          docker compose up -d --force-recreate
